# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            koakande01
tagline:          'Data Science, Machine Learning, Jekyll'
url:              http://www.koakande.com
shorturl:         koakande.com

author:
  name:           'koakande'
  url:            https://twitter.com/koakande

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/kbakande/kbakande.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Blog: '/blog/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
